version: "3.9"

services:
  web:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/ktor
      - DB_DRIVER=org.postgresql.Driver
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - JWT_SECRET=123
      - JWT_VALIDITY_MS=36000000
      - JWT_ISSUER=blockotlin
      - JWT_REALM=blockotlin.blockotlin-api
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ktor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: