services:
  - name: blockotlin-service
    type: web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8081"
    healthCheckPath: /
    region: oregon
    buildCommand: gradle shadowJar --no-daemon
